user:
  name: 
  avatar: /images/avatar.jpg
  location:
  description:
  footnotes:

# config you SNS
social:
  zhihu:
  twitter:
  facebook:
  linkedin:
  instagram:
  github: haojen

# Page icon
favicon: images/favicon.ico

friend_links:
  - title: Link1
    link: https://www.link1.test.com/

    
#https://github.com/haojen/hexo-theme-Claudia